name: HDIファイル更新

on:
  workflow_dispatch:  # 手動で実行できるようにする

jobs:
  update_hdi:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v2

      - name: 必要なツールのインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip zip

      - name: ZIPファイルの解凍
        run: |
          # hdi.zipを解凍してHDIファイルを取得
          unzip -o hdi.zip

      - name: HDIファイルにMP3を追加
        run: |
          # HDIファイルをマウントするためのディレクトリを作成
          mkdir -p hdi_mount
          # HDIファイルをマウント
          sudo mount -o loop hdd40\(boot\)\(win3.1\ Installed\).hdi hdi_mount
          # MP3ファイルをHDIファイルにコピー
          cp input.mp3 hdi_mount/
          # HDIファイルのマウントを解除
          sudo umount hdi_mount

      - name: 更新されたHDIファイルをZIPに圧縮
        run: |
          # 更新されたHDIファイルをZIP形式で圧縮
          zip updated_hdi.zip hdd40\(boot\)\(win3.1\ Installed\).hdi

      - name: 更新されたZIPファイルをリポジトリにアップロード
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const filePath = path.join(process.cwd(), 'updated_hdi.zip');
            const content = fs.readFileSync(filePath);
            const base64Content = Buffer.from(content).toString('base64');

            const { data: { sha } } = await github.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'updated_hdi.zip',
            }).catch(() => ({ data: { sha: null } }));

            await github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'updated_hdi.zip',
              message: 'Update HDI ZIP file',
              content: base64Content,
              sha: sha,
            });
