name: Build PC-98 HDI with WAV Player

on:
  workflow_dispatch:  # 手動実行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y ffmpeg unzip zip kpartx

      - name: Unzip HDI File
        run: unzip hdd40.zip

      - name: Convert MP3 to WAV
        run: |
          ffmpeg -i input.mp3 -ac 1 -ar 22050 -f wav -bitexact output.wav

      - name: Download WPLAY
        run: |
          curl -L -o WPLAY.COM https://nfggames.com/forum2/index.php?action=dlattach;topic=5607.0;attach=1210

      - name: Create Batch File
        run: echo "WPLAY output.wav" > playwav.bat

      - name: Setup Loopback Device
        run: |
          sudo losetup -fP "hdd40(boot)(win3.1 Installed).hdi"
          sudo kpartx -av "hdd40(boot)(win3.1 Installed).hdi"

      - name: Detect Partitions
        run: |
          sudo fdisk -l "hdd40(boot)(win3.1 Installed).hdi"

      - name: Mount and Copy Files
        run: |
          mkdir -p mnt
          sudo mount /dev/loop0p1 mnt
          sudo cp WPLAY.COM mnt/
          sudo cp output.wav mnt/
          sudo cp playwav.bat mnt/
          sudo umount mnt
          sudo losetup -d /dev/loop0

      - name: Compress Final HDI
        run: zip hdd40_final.zip "hdd40(boot)(win3.1 Installed).hdi"

      - name: Upload HDI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pc98-disk-image
          path: hdd40_final.zip
