name: Build PC-98 HDI with WAV Player
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg unzip zip qemu-utils

      - name: Unzip HDI File
        run: unzip hdd40.zip
        
      - name: Rename HDI file
        run: |
          mv "hdd40(boot)(win3.1 Installed).hdi" hdd40.hdi

      - name: Convert MP3 to WAV
        run: |
          ffmpeg -i input.mp3 -ac 1 -ar 22050 -f wav -bitexact output.wav

      - name: Download WPLAY
        run: |
          curl -L -o WPLAY.COM https://nfggames.com/forum2/index.php?action=dlattach;topic=5607.0;attach=1210

      - name: Create Batch File
        run: echo "WPLAY output.wav" > playwav.bat

      - name: Setup loop device and mount
        run: |
          # イメージをループデバイスとしてセットアップ
          LOOPDEV=$(sudo losetup --find --show hdd40.hdi)
          echo "Loop device is $LOOPDEV"
          
          # マウントポイントを作成
          sudo mkdir -p /mnt/pc98
          
          # FAT12としてマウント試行
          sudo mount -t msdos -o fat=12 $LOOPDEV /mnt/pc98 || \
          # FAT16としてマウント試行
          sudo mount -t msdos -o fat=16 $LOOPDEV /mnt/pc98 || \
          # 通常のFATとしてマウント試行
          sudo mount -t msdos $LOOPDEV /mnt/pc98
          
          # ファイルをコピー
          sudo cp WPLAY.COM /mnt/pc98/
          sudo cp output.wav /mnt/pc98/
          sudo cp playwav.bat /mnt/pc98/
          
          # アンマウントとクリーンアップ
          sudo umount /mnt/pc98
          sudo losetup -d $LOOPDEV

      - name: Rename back HDI file
        run: |
          mv hdd40.hdi "hdd40(boot)(win3.1 Installed).hdi"

      - name: Compress Final HDI
        run: zip hdd40_final.zip "hdd40(boot)(win3.1 Installed).hdi"

      - name: Upload HDI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pc98-disk-image
          path: hdd40_final.zip
