name: Extract HDI Files

on:
  push:
    branches:
      - main

jobs:
  extract_hdi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用するPythonのバージョンを指定

    - name: Install required packages
      run: |
        pip install pyhdi  # HDIファイルを扱うためのライブラリをインストール

    - name: Run HDI extraction script
      run: |
        python script.py "./【PC98】雫.hdi"  # HDIファイルを解析するPythonスクリプトを実行

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add extracted_files/*.txt  # 生成されたテキストファイルを追加
        git commit -m "Extracted files from HDI and converted to text"
        git push
