name: Update HDI Files

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-hdi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install HDI Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mtools qemu-utils

      - name: Set Unique HDI Filename
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          echo "HDI_FILENAME=【PC98】雫_${TIMESTAMP}.hdi" >> $GITHUB_ENV

      - name: Copy HDI with New Name
        run: |
          cp "【PC98】雫.hdi" "${{ env.HDI_FILENAME }}"

      - name: Modify HDI
        run: |
          sudo ./modify_hdi.py "${{ env.HDI_FILENAME }}" file_list.txt "gen_ts1.exe"

      - name: Commit and push HDI file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 変更があれば、一時的に保存
          git stash

          # リモートの最新状態を取得
          git pull --rebase origin main || true

          # 一時保存していた変更を戻す
          git stash pop || true

          # HDIのタイムスタンプを更新（変更を確実に検出させる）
          touch "${{ env.HDI_FILENAME }}"

          # ファイルを Git に追加
          git add "${{ env.HDI_FILENAME }}" CONFIG.SYS GENSOU/

          # 変更があればコミット
          git commit -m "Updated HDI file (${GITHUB_ENV}) and system files" || echo "No changes to commit"

          # 変更をプッシュ
          git push origin main

      - name: Upload HDI to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ env.HDI_FILENAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
