name: Convert MP3 to HDI

on:
  push:  # プッシュイベントでトリガー
    branches:
      - main  # メインブランチにプッシュされたときに実行
  workflow_dispatch:  # 手動トリガーを設定

jobs:
  convert:
    runs-on: ubuntu-latest  # Ubuntu環境で実行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # リポジトリをチェックアウト

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mtools  # mtoolsをインストール
          sudo apt-get install -y zip  # ZIP圧縮ツールをインストール
          sudo apt-get install -y dosfstools  # FATファイルシステムを作成するためのツール

      - name: Create HDI and copy MP3 files
        run: |
          HDI_FILE="output.img"
          MP3_FILES=$(find . -name "*.mp3")

          # 空のイメージファイルを作成
          dd if=/dev/zero of=$HDI_FILE bs=1M count=10  # 10MBのイメージファイルを作成

          # FATファイルシステムを作成
          mkfs.msdos $HDI_FILE

          # mtoolsを使用してファイルをコピー
          mcopy -i $HDI_FILE $MP3_FILES ::/

      - name: Check HDI file size
        id: check_size
        run: |
          SIZE=$(stat -c%s "output.img")
          echo "HDI file size: $SIZE bytes"
          echo "::set-output name=size::$SIZE"

      - name: Upload HDI or ZIP
        run: |
          if [ "${{ steps.check_size.outputs.size }}" -gt 10485760 ]; then  # 10MB
            echo "HDI file is too large, compressing to ZIP"
            zip output.zip output.img
            echo "Uploading ZIP file"
            gh release upload "latest" output.zip
          else
            echo "Uploading HDI file"
            gh release upload "latest" output.img
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
